Exception handling middleware
nantonov/KCHAU pull request #27
Opened 2022-02-25 11:36 UTC by CrazyKamenwik

2022-02-25 13:12 UTC, nantonov requested changes

2022-02-25 13:12 UTC, nantonov commented on BookShop/BookShop.API/Controllers/AuthorController.cs
> +                _logger.LogError($"No author with {model.Id} ID.");
no need here

2022-02-25 13:12 UTC, nantonov commented on BookShop/BookShop.API/Controllers/CustomerController.cs
> +            _logger = logger;
no need

2022-02-25 13:12 UTC, nantonov commented on BookShop/BookShop.API/Middlewares/ExceptionMiddleware.cs
> +            //private async Task HandleExceptionAsync(HttpContext context, Exception exception)
del

2022-02-25 13:12 UTC, nantonov commented on BookShop/BookShop.BLL/Handlers/OrderHandlers/OrderRequestsHandler.cs
> +                //TotalPrice = request.TotalPrice,
del

2022-02-25 13:12 UTC, nantonov commented on BookShop/BookShop.BLL/Handlers/OrderHandlers/OrderRequestsHandler.cs
> +                //TotalPrice = request.TotalPrice,
del

2022-02-25 13:12 UTC, nantonov commented on BookShop/BookShop.BLL/Handlers/OrderHandlers/OrderRequestsHandler.cs
> +            //var order = new OrderEntity
del

2022-02-28 09:05 UTC, hromau approved these changes

2022-02-28 09:24 UTC, Blackolf931 approved these changes

2022-02-28 09:25 UTC, VadimZharikov approved these changes

2022-02-28 09:29 UTC, nantonov approved these changes

2022-02-28 09:30 UTC, merged