Feature/book api
nantonov/KCHAU pull request #8
Opened 2021-12-21 10:44 UTC by CrazyKamenwik

2021-12-21 12:35 UTC, nantonov requested changes

2021-12-21 12:35 UTC, nantonov commented on BookOrderApi/BookOrderApi/AppDbContext.cs
> +        //protected override void OnModelCreating(ModelBuilder modelBuilder)
Get rid of comments

2021-12-21 12:35 UTC, nantonov commented on BookOrderApi/BookOrderApi/Controllers/BookController.cs
> +        //private readonly HttpContextAccessor _httpcontext;
Get rid of comments

2021-12-21 12:35 UTC, nantonov commented on BookOrderApi/BookOrderApi/Controllers/BookController.cs
> +            //_httpcontext = httpContext;
Get rid of comments

2021-12-21 12:35 UTC, nantonov commented on BookOrderApi/BookOrderApi/Entities/BookAuthor.cs
> +﻿//namespace BookOrderApi.Entities
Get rid of comments

2021-12-21 12:35 UTC, nantonov commented on BookOrderApi/BookOrderApi/Entities/BookOrder.cs
> +﻿//namespace BookOrderApi.Entities
Get rid of comments

2021-12-21 12:35 UTC, nantonov commented on BookOrderApi/BookOrderApi/Entities/Order.cs
> +        public int CustomerId { get; set; }
Add navigation prop for Customer

2021-12-21 12:35 UTC, nantonov commented on BookOrderApi/BookOrderApi/desktop.ini
> +[ViewState]
Del this file

2021-12-21 12:43 UTC, CrazyKamenwik commented on BookOrderApi/BookOrderApi/Entities/BookOrder.cs
> +﻿//namespace BookOrderApi.Entities
> Get rid of comments

may be I should delete these files in case of their creation by ef core?

2021-12-21 12:53 UTC, nantonov commented on BookOrderApi/BookOrderApi/Entities/BookOrder.cs
> +﻿//namespace BookOrderApi.Entities
+

2021-12-22 14:42 UTC, nantonov requested changes

2021-12-22 14:42 UTC, nantonov commented on BookOrderApi/BookOrderApi/BookOrderApi.csproj
> +  <ItemGroup>
Delete this ItemGroup section

2021-12-22 14:42 UTC, nantonov commented on BookOrderApi/BookOrderApi/Controllers/BookController.cs
> +            var data = _dbcontext.Books
unnecessary

2021-12-22 14:42 UTC, nantonov commented on BookOrderApi/BookOrderApi/Controllers/BookController.cs
> +            var aut = _dbcontext.Authors
Update naming

2021-12-22 14:42 UTC, nantonov commented on BookOrderApi/BookOrderApi/Controllers/BookController.cs
> +        public IActionResult Index()
Returns Authors, but controller named as Book

2021-12-22 15:10 UTC, nantonov requested changes

2021-12-22 15:10 UTC, nantonov commented on BookOrderApi/BookOrderApi/Controllers/BookController.cs
> +            var books = _dbcontext.Books;
ToList

2021-12-22 15:16 UTC, nantonov approved these changes

2021-12-23 07:15 UTC, hromau approved these changes

2021-12-23 07:47 UTC, merged